version: 2
jobs:
  build:
    docker:
      - image: sgalkin/carnd-t2-build:latest
    steps:
      - checkout
      - run:
          command: |  
            echo "Building project"
            mkdir -p build
            cd build
            cmake ..
            make -j
            make test

workflows:
  version: 2
  build:
    jobs:
      - build
